# Generated by Django 6.0.2 on 2026-02-07 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_description', models.TextField()),
                ('address', models.TextField()),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturer', 'Manufacturer'), ('service', 'Service')], max_length=20)),
                ('id_type', models.CharField(choices=[('gst', 'GST'), ('pan', 'PAN')], max_length=10)),
                ('id_number', models.CharField(max_length=50)),
                ('id_proof_file', models.FileField(upload_to='vendor_docs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
