# Generated by Django 6.0.2 on 2026-02-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_alter_vendorprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_number',
            field=models.CharField(blank=True, help_text='15-digit GST number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_card_file',
            field=models.FileField(blank=True, help_text='Upload PAN card image', null=True, upload_to='pan_cards/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_name',
            field=models.CharField(blank=True, help_text='Name as per PAN card', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pan_number',
            field=models.CharField(blank=True, help_text='10-character PAN number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('gst', 'GST'), ('pan', 'PAN')], max_length=10, null=True),
        ),
    ]
