# Generated by Django 5.2 on 2026-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_authuser_id_alter_cart_id_alter_cartitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_names',
            field=models.TextField(default=''),
        ),
    ]
